# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude_types: [markdown]
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        # Uncomment in case the mirror jumps to pre-releases
        #additional_dependencies:
        #[
        # https://www.npmjs.com/package/prettier
        #"prettier@3.0.3"
        #]
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "2.7.2"
    hooks:
      - id: editorconfig-checker
        alias: ec
