homeserver:
  domain: "localhost:9999"
  url: http://localhost:8081

db:
  engine: "postgres"
  connectionString: "postgres://mjolnir-tester:mjolnir-test@127.0.0.1:8083/mjolnir-test-db"

adminRoom: "#draupnir-admin:localhost:9999"

webAPI:
  port: 9001
